version: '3.1'

services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: aladino
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080